//! Vim script built-in functions database

/// Function availability in Vim/Neovim
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Availability {
    /// Available in both Vim and Neovim
    Common,
    /// Vim only (e.g., ch_*, job_*, popup_*, term_*)
    VimOnly,
    /// Neovim only (e.g., nvim_*, api_info, stdpath)
    NeovimOnly,
}

/// Information about a built-in function
pub struct BuiltinFunction {
    pub name: &'static str,
    pub signature: &'static str,
    pub description: &'static str,
    pub availability: Availability,
}

/// List of Vim built-in functions
/// Reference: :help function-list
pub static BUILTIN_FUNCTIONS: &[BuiltinFunction] = &[
    // String functions
    BuiltinFunction {
        name: "strlen",
        signature: "strlen({string})",
        description: "Return the number of bytes in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strchars",
        signature: "strchars({string} [, {skipcc}])",
        description: "Return the number of characters in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strwidth",
        signature: "strwidth({string})",
        description: "Return the display width of {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strdisplaywidth",
        signature: "strdisplaywidth({string} [, {col}])",
        description: "Return the display width of {string} starting at {col}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "substitute",
        signature: "substitute({string}, {pat}, {sub}, {flags})",
        description: "Replace {pat} with {sub} in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "submatch",
        signature: "submatch({nr} [, {list}])",
        description: "Return a specific match in substitute",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strpart",
        signature: "strpart({string}, {start} [, {len} [, {chars}]])",
        description: "Return part of a string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "stridx",
        signature: "stridx({haystack}, {needle} [, {start}])",
        description: "Return index of {needle} in {haystack}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strridx",
        signature: "strridx({haystack}, {needle} [, {start}])",
        description: "Return last index of {needle} in {haystack}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "split",
        signature: "split({string} [, {pattern} [, {keepempty}]])",
        description: "Split {string} into a List",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "join",
        signature: "join({list} [, {sep}])",
        description: "Join {list} items into a string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "trim",
        signature: "trim({string} [, {mask} [, {dir}]])",
        description: "Remove characters from {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tolower",
        signature: "tolower({string})",
        description: "Convert {string} to lowercase",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "toupper",
        signature: "toupper({string})",
        description: "Convert {string} to uppercase",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tr",
        signature: "tr({string}, {fromstr}, {tostr})",
        description: "Translate characters in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "printf",
        signature: "printf({fmt}, {expr1}...)",
        description: "Format a string like sprintf()",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "escape",
        signature: "escape({string}, {chars})",
        description: "Escape {chars} in {string} with backslash",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "shellescape",
        signature: "shellescape({string} [, {special}])",
        description: "Escape {string} for use as shell argument",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "fnameescape",
        signature: "fnameescape({string})",
        description: "Escape {string} for use as file name",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "match",
        signature: "match({string}, {pattern} [, {start} [, {count}]])",
        description: "Return index of {pattern} match in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchend",
        signature: "matchend({string}, {pattern} [, {start} [, {count}]])",
        description: "Return end index of {pattern} match",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchstr",
        signature: "matchstr({string}, {pattern} [, {start} [, {count}]])",
        description: "Return matched string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchlist",
        signature: "matchlist({string}, {pattern} [, {start} [, {count}]])",
        description: "Return match and submatches as List",
        availability: Availability::Common,
    },
    // List functions
    BuiltinFunction {
        name: "len",
        signature: "len({expr})",
        description: "Return the length of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "empty",
        signature: "empty({expr})",
        description: "Return TRUE if {expr} is empty",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "get",
        signature: "get({list}, {idx} [, {default}])",
        description: "Get item {idx} from {list}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "add",
        signature: "add({list}, {expr})",
        description: "Append {expr} to {list}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "insert",
        signature: "insert({list}, {item} [, {idx}])",
        description: "Insert {item} into {list}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "remove",
        signature: "remove({list}, {idx} [, {end}])",
        description: "Remove items from {list}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "copy",
        signature: "copy({expr})",
        description: "Make a shallow copy of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "deepcopy",
        signature: "deepcopy({expr} [, {noref}])",
        description: "Make a deep copy of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "extend",
        signature: "extend({list1}, {list2} [, {idx}])",
        description: "Append {list2} to {list1}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "filter",
        signature: "filter({expr}, {func})",
        description: "Filter items in {expr} using {func}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "map",
        signature: "map({expr}, {func})",
        description: "Transform items in {expr} using {func}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "sort",
        signature: "sort({list} [, {func} [, {dict}]])",
        description: "Sort {list} in-place",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "reverse",
        signature: "reverse({list})",
        description: "Reverse {list} in-place",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "uniq",
        signature: "uniq({list} [, {func} [, {dict}]])",
        description: "Remove duplicate adjacent items",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "index",
        signature: "index({list}, {expr} [, {start} [, {ic}]])",
        description: "Return index of {expr} in {list}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "count",
        signature: "count({list}, {expr} [, {ic} [, {max}]])",
        description: "Count occurrences of {expr} in {list}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "range",
        signature: "range({expr} [, {max} [, {stride}]])",
        description: "Return a List of numbers",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "repeat",
        signature: "repeat({expr}, {count})",
        description: "Repeat {expr} {count} times",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "flatten",
        signature: "flatten({list} [, {maxdepth}])",
        description: "Flatten nested lists",
        availability: Availability::Common,
    },
    // Dictionary functions
    BuiltinFunction {
        name: "keys",
        signature: "keys({dict})",
        description: "Return List of keys in {dict}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "values",
        signature: "values({dict})",
        description: "Return List of values in {dict}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "items",
        signature: "items({dict})",
        description: "Return List of [key, value] pairs",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "has_key",
        signature: "has_key({dict}, {key})",
        description: "Return TRUE if {dict} has {key}",
        availability: Availability::Common,
    },
    // Type checking
    BuiltinFunction {
        name: "type",
        signature: "type({expr})",
        description: "Return the type of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "typename",
        signature: "typename({expr})",
        description: "Return the type name of {expr}",
        availability: Availability::Common,
    },
    // Buffer/Window/Tab functions
    BuiltinFunction {
        name: "bufnr",
        signature: "bufnr([{expr} [, {create}]])",
        description: "Return buffer number",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "bufname",
        signature: "bufname([{expr}])",
        description: "Return buffer name",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "bufexists",
        signature: "bufexists({expr})",
        description: "Return TRUE if buffer exists",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "buflisted",
        signature: "buflisted({expr})",
        description: "Return TRUE if buffer is listed",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "bufloaded",
        signature: "bufloaded({expr})",
        description: "Return TRUE if buffer is loaded",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getbufline",
        signature: "getbufline({buf}, {lnum} [, {end}])",
        description: "Return lines from buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setbufline",
        signature: "setbufline({buf}, {lnum}, {text})",
        description: "Set lines in buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "appendbufline",
        signature: "appendbufline({buf}, {lnum}, {text})",
        description: "Append lines to buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "deletebufline",
        signature: "deletebufline({buf}, {first} [, {last}])",
        description: "Delete lines from buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winnr",
        signature: "winnr([{arg}])",
        description: "Return window number",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winbufnr",
        signature: "winbufnr({nr})",
        description: "Return buffer number of window {nr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tabpagenr",
        signature: "tabpagenr([{arg}])",
        description: "Return tab page number",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tabpagebuflist",
        signature: "tabpagebuflist([{arg}])",
        description: "Return List of buffer numbers in tab",
        availability: Availability::Common,
    },
    // Cursor/Position functions
    BuiltinFunction {
        name: "line",
        signature: "line({expr} [, {winid}])",
        description: "Return line number of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "col",
        signature: "col({expr} [, {winid}])",
        description: "Return column number of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "virtcol",
        signature: "virtcol({expr} [, {list} [, {winid}]])",
        description: "Return screen column of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getpos",
        signature: "getpos({expr})",
        description: "Return position of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setpos",
        signature: "setpos({expr}, {list})",
        description: "Set position of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "cursor",
        signature: "cursor({lnum}, {col} [, {off}])",
        description: "Move cursor to position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcurpos",
        signature: "getcurpos([{winnr}])",
        description: "Return cursor position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getline",
        signature: "getline({lnum} [, {end}])",
        description: "Return line(s) from current buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setline",
        signature: "setline({lnum}, {text})",
        description: "Set line {lnum} to {text}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "append",
        signature: "append({lnum}, {text})",
        description: "Append {text} after line {lnum}",
        availability: Availability::Common,
    },
    // Search functions
    BuiltinFunction {
        name: "search",
        signature: "search({pattern} [, {flags} [, {stopline} [, {timeout} [, {skip}]]]])",
        description: "Search for {pattern}, return line number of match",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "searchpos",
        signature: "searchpos({pattern} [, {flags} [, {stopline} [, {timeout} [, {skip}]]]])",
        description: "Search for {pattern}, return [lnum, col] of match",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "searchpair",
        signature: "searchpair({start}, {middle}, {end} [, {flags} [, {skip} [, {stopline} [, {timeout}]]]])",
        description: "Search for matching pair of start/end patterns",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "searchpairpos",
        signature: "searchpairpos({start}, {middle}, {end} [, {flags} [, {skip} [, {stopline} [, {timeout}]]]])",
        description: "Search for matching pair, return [lnum, col]",
        availability: Availability::Common,
    },
    // File functions
    BuiltinFunction {
        name: "expand",
        signature: "expand({string} [, {nosuf} [, {list}]])",
        description: "Expand wildcards and special keywords",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "glob",
        signature: "glob({expr} [, {nosuf} [, {list} [, {alllinks}]]])",
        description: "Expand file wildcards",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "globpath",
        signature: "globpath({path}, {expr} [, {nosuf} [, {list} [, {alllinks}]]])",
        description: "Expand file wildcards in {path}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "filereadable",
        signature: "filereadable({file})",
        description: "Return TRUE if {file} is readable",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "filewritable",
        signature: "filewritable({file})",
        description: "Return TRUE if {file} is writable",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "isdirectory",
        signature: "isdirectory({directory})",
        description: "Return TRUE if {directory} is a directory",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "fnamemodify",
        signature: "fnamemodify({fname}, {mods})",
        description: "Modify file name according to {mods}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "readfile",
        signature: "readfile({fname} [, {type} [, {max}]])",
        description: "Read file into a List",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "writefile",
        signature: "writefile({list}, {fname} [, {flags}])",
        description: "Write List to file",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "delete",
        signature: "delete({fname} [, {flags}])",
        description: "Delete file or directory",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "rename",
        signature: "rename({from}, {to})",
        description: "Rename file",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "mkdir",
        signature: "mkdir({name} [, {path} [, {prot}]])",
        description: "Create directory",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcwd",
        signature: "getcwd([{winnr} [, {tabnr}]])",
        description: "Return current working directory",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "chdir",
        signature: "chdir({dir})",
        description: "Change current directory",
        availability: Availability::Common,
    },
    // System functions
    BuiltinFunction {
        name: "system",
        signature: "system({cmd} [, {input}])",
        description: "Execute shell command and return output",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "systemlist",
        signature: "systemlist({cmd} [, {input} [, {keepempty}]])",
        description: "Execute shell command and return List",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "executable",
        signature: "executable({expr})",
        description: "Return TRUE if {expr} is executable",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "exepath",
        signature: "exepath({expr})",
        description: "Return full path to executable",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "environ",
        signature: "environ()",
        description: "Return Dict of environment variables",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getenv",
        signature: "getenv({name})",
        description: "Return environment variable value",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setenv",
        signature: "setenv({name}, {val})",
        description: "Set environment variable",
        availability: Availability::Common,
    },
    // Misc functions
    BuiltinFunction {
        name: "exists",
        signature: "exists({expr})",
        description: "Return TRUE if {expr} exists",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "has",
        signature: "has({feature} [, {check}])",
        description: "Return TRUE if feature is supported",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "eval",
        signature: "eval({string})",
        description: "Evaluate {string} as expression",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "execute",
        signature: "execute({command} [, {silent}])",
        description: "Execute Ex command and return output",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "input",
        signature: "input({prompt} [, {text} [, {completion}]])",
        description: "Get input from user",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "confirm",
        signature: "confirm({msg} [, {choices} [, {default} [, {type}]]])",
        description: "Show confirmation dialog",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "feedkeys",
        signature: "feedkeys({string} [, {mode}])",
        description: "Add keys to input buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "mode",
        signature: "mode([{expr}])",
        description: "Return current mode",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "visualmode",
        signature: "visualmode([{expr}])",
        description: "Return last visual mode",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "echo",
        signature: "echo {expr1} ..",
        description: "Echo expressions",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "echomsg",
        signature: "echomsg {expr1} ..",
        description: "Echo as message",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "echoerr",
        signature: "echoerr {expr1} ..",
        description: "Echo as error message",
        availability: Availability::Common,
    },
    // Function-related
    BuiltinFunction {
        name: "call",
        signature: "call({func}, {arglist} [, {dict}])",
        description: "Call {func} with arguments from {arglist}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "function",
        signature: "function({name} [, {arglist}] [, {dict}])",
        description: "Return Funcref to function {name}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "funcref",
        signature: "funcref({name} [, {arglist}] [, {dict}])",
        description: "Return Funcref like function()",
        availability: Availability::Common,
    },
    // JSON
    BuiltinFunction {
        name: "json_encode",
        signature: "json_encode({expr})",
        description: "Encode {expr} as JSON",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "json_decode",
        signature: "json_decode({string})",
        description: "Decode JSON {string}",
        availability: Availability::Common,
    },
    // Timer
    BuiltinFunction {
        name: "timer_start",
        signature: "timer_start({time}, {callback} [, {options}])",
        description: "Create a timer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "timer_stop",
        signature: "timer_stop({timer})",
        description: "Stop a timer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "timer_stopall",
        signature: "timer_stopall()",
        description: "Stop all timers",
        availability: Availability::Common,
    },
    // Math functions
    BuiltinFunction {
        name: "abs",
        signature: "abs({expr})",
        description: "Return absolute value of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "acos",
        signature: "acos({expr})",
        description: "Return arc cosine of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "asin",
        signature: "asin({expr})",
        description: "Return arc sine of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "atan",
        signature: "atan({expr})",
        description: "Return arc tangent of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "atan2",
        signature: "atan2({expr1}, {expr2})",
        description: "Return arc tangent of {expr1}/{expr2}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "ceil",
        signature: "ceil({expr})",
        description: "Return smallest integer >= {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "cos",
        signature: "cos({expr})",
        description: "Return cosine of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "cosh",
        signature: "cosh({expr})",
        description: "Return hyperbolic cosine of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "exp",
        signature: "exp({expr})",
        description: "Return e to the power of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "floor",
        signature: "floor({expr})",
        description: "Return largest integer <= {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "fmod",
        signature: "fmod({expr1}, {expr2})",
        description: "Return remainder of {expr1}/{expr2}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "log",
        signature: "log({expr})",
        description: "Return natural logarithm of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "log10",
        signature: "log10({expr})",
        description: "Return base-10 logarithm of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "pow",
        signature: "pow({x}, {y})",
        description: "Return {x} to the power of {y}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "round",
        signature: "round({expr})",
        description: "Return {expr} rounded to nearest integer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "sin",
        signature: "sin({expr})",
        description: "Return sine of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "sinh",
        signature: "sinh({expr})",
        description: "Return hyperbolic sine of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "sqrt",
        signature: "sqrt({expr})",
        description: "Return square root of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tan",
        signature: "tan({expr})",
        description: "Return tangent of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tanh",
        signature: "tanh({expr})",
        description: "Return hyperbolic tangent of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "trunc",
        signature: "trunc({expr})",
        description: "Return integer part of {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "float2nr",
        signature: "float2nr({expr})",
        description: "Convert Float to Number",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "str2float",
        signature: "str2float({string})",
        description: "Convert String to Float",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "str2nr",
        signature: "str2nr({string} [, {base}])",
        description: "Convert String to Number",
        availability: Availability::Common,
    },
    // Character/byte conversion
    BuiltinFunction {
        name: "char2nr",
        signature: "char2nr({string} [, {utf8}])",
        description: "Return number value of first char in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "nr2char",
        signature: "nr2char({expr} [, {utf8}])",
        description: "Return character with number value {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "byteidx",
        signature: "byteidx({expr}, {nr} [, {utf16}])",
        description: "Return byte index of {nr}th char in {expr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "byteidxcomp",
        signature: "byteidxcomp({expr}, {nr} [, {utf16}])",
        description: "Like byteidx() but count composing chars",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "charidx",
        signature: "charidx({string}, {idx} [, {countcc} [, {utf16}]])",
        description: "Return char index of byte {idx} in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strgetchar",
        signature: "strgetchar({str}, {index})",
        description: "Return char at {index} in {str}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strcharpart",
        signature: "strcharpart({str}, {start} [, {len} [, {skipcc}]])",
        description: "Return part of {str} by char index",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strcharlen",
        signature: "strcharlen({string})",
        description: "Return number of chars in {string}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "str2list",
        signature: "str2list({string} [, {utf8}])",
        description: "Return List of character numbers",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "list2str",
        signature: "list2str({list} [, {utf8}])",
        description: "Return String from List of numbers",
        availability: Availability::Common,
    },
    // Window functions
    BuiltinFunction {
        name: "winheight",
        signature: "winheight({nr})",
        description: "Return height of window {nr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winwidth",
        signature: "winwidth({nr})",
        description: "Return width of window {nr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winline",
        signature: "winline()",
        description: "Return window line of cursor",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "wincol",
        signature: "wincol()",
        description: "Return window column of cursor",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winsaveview",
        signature: "winsaveview()",
        description: "Return Dict with current window view",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winrestview",
        signature: "winrestview({dict})",
        description: "Restore window view from {dict}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_getid",
        signature: "win_getid([{win} [, {tab}]])",
        description: "Return window ID",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_gotoid",
        signature: "win_gotoid({id})",
        description: "Go to window with {id}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_id2win",
        signature: "win_id2win({id})",
        description: "Return window number of {id}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_id2tabwin",
        signature: "win_id2tabwin({id})",
        description: "Return [tabnr, winnr] of {id}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_findbuf",
        signature: "win_findbuf({bufnr})",
        description: "Return window IDs for {bufnr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_gettype",
        signature: "win_gettype([{nr}])",
        description: "Return type of window {nr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_screenpos",
        signature: "win_screenpos({nr})",
        description: "Return screen position of window {nr}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_execute",
        signature: "win_execute({id}, {command} [, {silent}])",
        description: "Execute {command} in window {id}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "win_splitmove",
        signature: "win_splitmove({nr}, {target} [, {options}])",
        description: "Move window {nr} to split of {target}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winlayout",
        signature: "winlayout([{tabnr}])",
        description: "Return layout of windows in tab",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "winrestcmd",
        signature: "winrestcmd()",
        description: "Return command to restore window sizes",
        availability: Availability::Common,
    },
    // Buffer info functions
    BuiltinFunction {
        name: "getbufinfo",
        signature: "getbufinfo([{buf}])",
        description: "Return List of buffer information",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getbufvar",
        signature: "getbufvar({buf}, {varname} [, {def}])",
        description: "Return variable from buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setbufvar",
        signature: "setbufvar({buf}, {varname}, {val})",
        description: "Set variable in buffer",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "bufadd",
        signature: "bufadd({name})",
        description: "Add buffer {name} to buffer list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "bufload",
        signature: "bufload({buf})",
        description: "Load buffer {buf} if not loaded",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getwininfo",
        signature: "getwininfo([{winid}])",
        description: "Return List of window information",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getwinvar",
        signature: "getwinvar({winnr}, {varname} [, {def}])",
        description: "Return variable from window",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setwinvar",
        signature: "setwinvar({winnr}, {varname}, {val})",
        description: "Set variable in window",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "gettabinfo",
        signature: "gettabinfo([{tabnr}])",
        description: "Return List of tab page information",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "gettabvar",
        signature: "gettabvar({tabnr}, {varname} [, {def}])",
        description: "Return variable from tab page",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "settabvar",
        signature: "settabvar({tabnr}, {varname}, {val})",
        description: "Set variable in tab page",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "gettabwinvar",
        signature: "gettabwinvar({tabnr}, {winnr}, {varname} [, {def}])",
        description: "Return variable from window in tab",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "settabwinvar",
        signature: "settabwinvar({tabnr}, {winnr}, {varname}, {val})",
        description: "Set variable in window of tab",
        availability: Availability::Common,
    },
    // Time functions
    BuiltinFunction {
        name: "localtime",
        signature: "localtime()",
        description: "Return current time in seconds",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strftime",
        signature: "strftime({format} [, {time}])",
        description: "Format time as string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "strptime",
        signature: "strptime({format}, {timestring})",
        description: "Parse time string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "reltime",
        signature: "reltime([{start} [, {end}]])",
        description: "Return relative time",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "reltimestr",
        signature: "reltimestr({time})",
        description: "Return string representation of reltime",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "reltimefloat",
        signature: "reltimefloat({time})",
        description: "Return Float from reltime",
        availability: Availability::Common,
    },
    // System info
    BuiltinFunction {
        name: "getpid",
        signature: "getpid()",
        description: "Return process ID of Vim",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "hostname",
        signature: "hostname()",
        description: "Return name of host machine",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tempname",
        signature: "tempname()",
        description: "Return name of a temp file",
        availability: Availability::Common,
    },
    // Input functions
    BuiltinFunction {
        name: "getchar",
        signature: "getchar([{expr}])",
        description: "Get one character from user",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcharstr",
        signature: "getcharstr([{expr}])",
        description: "Get one character as string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcharmod",
        signature: "getcharmod()",
        description: "Return modifiers for last getchar()",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "inputlist",
        signature: "inputlist({textlist})",
        description: "Let user pick from a list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "inputsecret",
        signature: "inputsecret({prompt} [, {text}])",
        description: "Get input without showing it",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "inputsave",
        signature: "inputsave()",
        description: "Save typeahead",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "inputrestore",
        signature: "inputrestore()",
        description: "Restore typeahead",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "inputdialog",
        signature: "inputdialog({prompt} [, {text} [, {cancelreturn}]])",
        description: "Like input() but in a GUI dialog",
        availability: Availability::Common,
    },
    // Match functions
    BuiltinFunction {
        name: "matchadd",
        signature: "matchadd({group}, {pattern} [, {priority} [, {id} [, {dict}]]])",
        description: "Add match highlighting",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchaddpos",
        signature: "matchaddpos({group}, {pos} [, {priority} [, {id} [, {dict}]]])",
        description: "Add match at positions",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matcharg",
        signature: "matcharg({nr})",
        description: "Return arguments of :match",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchdelete",
        signature: "matchdelete({id} [, {win}])",
        description: "Delete match by ID",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "clearmatches",
        signature: "clearmatches([{win}])",
        description: "Clear all matches",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getmatches",
        signature: "getmatches([{win}])",
        description: "Return list of matches",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setmatches",
        signature: "setmatches({list} [, {win}])",
        description: "Restore matches from list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchfuzzy",
        signature: "matchfuzzy({list}, {str} [, {dict}])",
        description: "Return fuzzy matches",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "matchfuzzypos",
        signature: "matchfuzzypos({list}, {str} [, {dict}])",
        description: "Return fuzzy matches with positions",
        availability: Availability::Common,
    },
    // Cursor/mark functions
    BuiltinFunction {
        name: "getcharpos",
        signature: "getcharpos({expr})",
        description: "Return char position of mark",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setcharpos",
        signature: "setcharpos({expr}, {list})",
        description: "Set char position of mark",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcursorcharpos",
        signature: "getcursorcharpos([{winnr}])",
        description: "Return cursor char position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setcursorcharpos",
        signature: "setcursorcharpos({lnum}, {col} [, {off}])",
        description: "Set cursor char position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "charcol",
        signature: "charcol({expr} [, {winid}])",
        description: "Return char column of position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getmarklist",
        signature: "getmarklist([{buf}])",
        description: "Return list of marks",
        availability: Availability::Common,
    },
    // File info functions
    BuiltinFunction {
        name: "getfsize",
        signature: "getfsize({fname})",
        description: "Return file size in bytes",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getftime",
        signature: "getftime({fname})",
        description: "Return file modification time",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getfperm",
        signature: "getfperm({fname})",
        description: "Return file permissions string",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setfperm",
        signature: "setfperm({fname}, {mode})",
        description: "Set file permissions",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getftype",
        signature: "getftype({fname})",
        description: "Return type of file",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "resolve",
        signature: "resolve({filename})",
        description: "Resolve symbolic links",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "simplify",
        signature: "simplify({filename})",
        description: "Simplify path without resolving links",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "pathshorten",
        signature: "pathshorten({path} [, {len}])",
        description: "Shorten directory names in path",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "isabsolutepath",
        signature: "isabsolutepath({path})",
        description: "Return TRUE if {path} is absolute",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "readdir",
        signature: "readdir({dir} [, {expr}])",
        description: "Return list of files in directory",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "readdirex",
        signature: "readdirex({dir} [, {expr} [, {dict}]])",
        description: "Return list of file info in directory",
        availability: Availability::Common,
    },
    // List functions
    BuiltinFunction {
        name: "min",
        signature: "min({expr})",
        description: "Return minimum value in list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "max",
        signature: "max({expr})",
        description: "Return maximum value in list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "reduce",
        signature: "reduce({object}, {func} [, {initial}])",
        description: "Reduce list to single value",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "mapnew",
        signature: "mapnew({expr1}, {expr2})",
        description: "Like map() but creates new list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "extendnew",
        signature: "extendnew({expr1}, {expr2} [, {expr3}])",
        description: "Like extend() but creates new list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "flattennew",
        signature: "flattennew({list} [, {maxdepth}])",
        description: "Like flatten() but creates new list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "indexof",
        signature: "indexof({object}, {expr} [, {opts}])",
        description: "Return index where {expr} is true",
        availability: Availability::Common,
    },
    // Quickfix/location list
    BuiltinFunction {
        name: "getqflist",
        signature: "getqflist([{what}])",
        description: "Return quickfix list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setqflist",
        signature: "setqflist({list} [, {action} [, {what}]])",
        description: "Set quickfix list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getloclist",
        signature: "getloclist({nr} [, {what}])",
        description: "Return location list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setloclist",
        signature: "setloclist({nr}, {list} [, {action} [, {what}]])",
        description: "Set location list",
        availability: Availability::Common,
    },
    // Jump/change list
    BuiltinFunction {
        name: "getjumplist",
        signature: "getjumplist([{winnr} [, {tabnr}]])",
        description: "Return jump list",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getchangelist",
        signature: "getchangelist([{buf}])",
        description: "Return change list",
        availability: Availability::Common,
    },
    // Tag functions
    BuiltinFunction {
        name: "taglist",
        signature: "taglist({expr} [, {filename}])",
        description: "Return list of matching tags",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "tagfiles",
        signature: "tagfiles()",
        description: "Return list of tag files",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "gettagstack",
        signature: "gettagstack([{winnr}])",
        description: "Return tag stack",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "settagstack",
        signature: "settagstack({winnr}, {dict} [, {action}])",
        description: "Set tag stack",
        availability: Availability::Common,
    },
    // Register functions
    BuiltinFunction {
        name: "getreg",
        signature: "getreg([{regname} [, 1 [, {list}]]])",
        description: "Return contents of register",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setreg",
        signature: "setreg({regname}, {value} [, {options}])",
        description: "Set register contents",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getregtype",
        signature: "getregtype([{regname}])",
        description: "Return type of register",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getreginfo",
        signature: "getreginfo([{regname}])",
        description: "Return info about register",
        availability: Availability::Common,
    },
    // Syntax/highlight functions
    BuiltinFunction {
        name: "synID",
        signature: "synID({lnum}, {col}, {trans})",
        description: "Return syntax ID at position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "synIDattr",
        signature: "synIDattr({synID}, {what} [, {mode}])",
        description: "Return attribute of syntax ID",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "synIDtrans",
        signature: "synIDtrans({synID})",
        description: "Return translated syntax ID",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "synstack",
        signature: "synstack({lnum}, {col})",
        description: "Return syntax ID stack at position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "synconcealed",
        signature: "synconcealed({lnum}, {col})",
        description: "Return concealed info at position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "hlID",
        signature: "hlID({name})",
        description: "Return highlight ID of {name}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "hlexists",
        signature: "hlexists({name})",
        description: "Return TRUE if highlight {name} exists",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "hlget",
        signature: "hlget([{name} [, {resolve}]])",
        description: "Return highlight definition",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "hlset",
        signature: "hlset({list})",
        description: "Set highlight definitions",
        availability: Availability::Common,
    },
    // Completion functions
    BuiltinFunction {
        name: "complete",
        signature: "complete({startcol}, {matches})",
        description: "Set completion matches",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "complete_add",
        signature: "complete_add({expr})",
        description: "Add completion match",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "complete_check",
        signature: "complete_check()",
        description: "Return TRUE if completion interrupted",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "complete_info",
        signature: "complete_info([{what}])",
        description: "Return completion information",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "pumvisible",
        signature: "pumvisible()",
        description: "Return TRUE if popup menu visible",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "pum_getpos",
        signature: "pum_getpos()",
        description: "Return position of popup menu",
        availability: Availability::Common,
    },
    // Command line functions
    BuiltinFunction {
        name: "getcmdline",
        signature: "getcmdline()",
        description: "Return current command line",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setcmdline",
        signature: "setcmdline({str} [, {pos}])",
        description: "Set command line contents",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcmdpos",
        signature: "getcmdpos()",
        description: "Return cursor position in cmdline",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "setcmdpos",
        signature: "setcmdpos({pos})",
        description: "Set cursor position in cmdline",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcmdtype",
        signature: "getcmdtype()",
        description: "Return current command line type",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcmdwintype",
        signature: "getcmdwintype()",
        description: "Return command line window type",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "getcompletion",
        signature: "getcompletion({pat}, {type} [, {filtered}])",
        description: "Return command line completions",
        availability: Availability::Common,
    },
    // Misc functions
    BuiltinFunction {
        name: "and",
        signature: "and({expr}, {expr})",
        description: "Bitwise AND",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "or",
        signature: "or({expr}, {expr})",
        description: "Bitwise OR",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "xor",
        signature: "xor({expr}, {expr})",
        description: "Bitwise XOR",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "invert",
        signature: "invert({expr})",
        description: "Bitwise invert",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "sha256",
        signature: "sha256({string})",
        description: "Return SHA256 checksum",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "rand",
        signature: "rand([{expr}])",
        description: "Return pseudo-random number",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "srand",
        signature: "srand([{expr}])",
        description: "Initialize random number seed",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "state",
        signature: "state([{what}])",
        description: "Return current state of Vim",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "undofile",
        signature: "undofile({name})",
        description: "Return undo file name for {name}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "undotree",
        signature: "undotree([{buf}])",
        description: "Return undo tree",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "shiftwidth",
        signature: "shiftwidth([{col}])",
        description: "Return effective shiftwidth value",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "wordcount",
        signature: "wordcount()",
        description: "Return word count statistics",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "nextnonblank",
        signature: "nextnonblank({lnum})",
        description: "Return line nr of next non-blank",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "prevnonblank",
        signature: "prevnonblank({lnum})",
        description: "Return line nr of prev non-blank",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "byte2line",
        signature: "byte2line({byte})",
        description: "Return line number at byte count",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "line2byte",
        signature: "line2byte({lnum})",
        description: "Return byte count at line",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "diff_filler",
        signature: "diff_filler({lnum})",
        description: "Return filler lines at {lnum}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "diff_hlID",
        signature: "diff_hlID({lnum}, {col})",
        description: "Return diff highlight ID",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "foldclosed",
        signature: "foldclosed({lnum})",
        description: "Return first line of fold at {lnum}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "foldclosedend",
        signature: "foldclosedend({lnum})",
        description: "Return last line of fold at {lnum}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "foldlevel",
        signature: "foldlevel({lnum})",
        description: "Return fold level at {lnum}",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "foldtext",
        signature: "foldtext()",
        description: "Return text for closed fold",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "foldtextresult",
        signature: "foldtextresult({lnum})",
        description: "Return text displayed for fold",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screenattr",
        signature: "screenattr({row}, {col})",
        description: "Return attribute at screen position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screenchar",
        signature: "screenchar({row}, {col})",
        description: "Return character at screen position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screenchars",
        signature: "screenchars({row}, {col})",
        description: "Return characters at screen position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screenstring",
        signature: "screenstring({row}, {col})",
        description: "Return string at screen position",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screenpos",
        signature: "screenpos({winid}, {lnum}, {col})",
        description: "Return screen position of text",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screencol",
        signature: "screencol()",
        description: "Return cursor screen column",
        availability: Availability::Common,
    },
    BuiltinFunction {
        name: "screenrow",
        signature: "screenrow()",
        description: "Return cursor screen row",
        availability: Availability::Common,
    },
    // Neovim-only functions
    BuiltinFunction {
        name: "stdpath",
        signature: "stdpath({what})",
        description: "Return standard path locations",
        availability: Availability::NeovimOnly,
    },
    BuiltinFunction {
        name: "api_info",
        signature: "api_info()",
        description: "Return API metadata",
        availability: Availability::NeovimOnly,
    },
];
